import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import type { ToolDefinition } from "../tool-registry.js";
import {
  DEFAULT_SD_SERVER_URL,
  detectLcmLora,
  pollJob,
  submitImgGen,
  type ImgGenRequest,
  type SdCapabilities,
} from "./sd-client.js";

export const genImageInputSchema = {
  prompt: z.string().min(1),
  negprompt: z.string().optional().default(""),
  width: z.number().int().positive().optional().default(512),
  height: z.number().int().positive().optional().default(512),
  seed: z.number().int().optional().default(-1),
  batch_count: z.number().int().min(1).max(8).optional().default(1),
  steps: z.number().int().min(1).max(150).optional().default(4),
  cfg: z.number().positive().optional().default(1.0),
  clip_skip: z.number().int().optional().default(-1),
  output_file: z.string().optional(),
};

export function buildSdToolDescription(capabilities?: SdCapabilities | null): string {
  const modelName = capabilities?.model?.name || capabilities?.model?.stem || "Stable Diffusion 1.5";
  const isSd15 = /sd1[._-]?5|v1[._-]?5|realistic|meina/i.test(modelName);
  const baseType = isSd15 ? "SD1.5" : "Stable Diffusion";

  return `Generate images using local Stable Diffusion (Model: ${modelName}, Base: ${baseType}, LCM accelerated). Built-in full VAE tiling enabled. Automatically saves generated images to workspace and returns base64 image content.`;
}

function generateTimestamp(): string {
  const now = new Date();
  const pad = (v: number) => String(v).padStart(2, "0");
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
}

export function createGenImageTool(
  sdServerUrl = DEFAULT_SD_SERVER_URL,
  capabilities?: SdCapabilities | null,
): ToolDefinition {
  const lcmLora = detectLcmLora(capabilities);

  return {
    name: "gen_image",
    title: "Generate Image",
    description: buildSdToolDescription(capabilities),
    inputSchema: genImageInputSchema,
    handler: async (input, context) => {
      const prompt = input.prompt as string;
      const userNeg = ((input.negprompt as string) || "").trim();
      const negative_prompt = userNeg
        ? `easynegative, negative_hand-neg, ${userNeg}`
        : "easynegative, negative_hand-neg";

      const width = Number(input.width ?? 512);
      const height = Number(input.height ?? 512);
      const seed = Number(input.seed ?? -1);
      const batch_count = Number(input.batch_count ?? 1);
      const steps = Number(input.steps ?? 4);
      const cfg = Number(input.cfg ?? 1.0);
      const clip_skip = Number(input.clip_skip ?? -1);
      const customOutputFile = input.output_file as string | undefined;

      const requestPayload: ImgGenRequest = {
        prompt,
        negative_prompt,
        width,
        height,
        seed,
        batch_count,
        clip_skip,
        ...(lcmLora ? { lora: [{ path: lcmLora.path || lcmLora.name || "", multiplier: 1.0 }] } : {}),
        sample_params: {
          scheduler: "lcm",
          sample_method: "lcm",
          sample_steps: steps,
          guidance: {
            txt_cfg: cfg,
          },
        },
        vae_tiling_params: {
          enabled: true,
          temporal_tiling: false,
          tile_size_x: 0,
          tile_size_y: 0,
          target_overlap: 0.5,
          rel_size_x: 0.0,
          rel_size_y: 0.0,
          extra_tiling_args: "",
        },
        output_format: "png",
        output_compression: 100,
      };

      const { id } = await submitImgGen(requestPayload, sdServerUrl);
      const completedJob = await pollJob(id, sdServerUrl);

      const images = completedJob.result?.images || [];
      if (images.length === 0) {
        throw new Error("No images were generated by the server.");
      }

      const stamp = generateTimestamp();
      const savedFiles: string[] = [];
      const content: Array<
        { type: "image"; data: string; mimeType: string } | { type: "text"; text: string }
      > = [];

      for (let i = 0; i < images.length; i++) {
        const img = images[i]!;
        content.push({
          type: "image",
          data: img.b64_json,
          mimeType: "image/png",
        });

        // Determine destination file path
        let destPath: string;
        if (customOutputFile) {
          if (images.length > 1) {
            const ext = path.extname(customOutputFile) || ".png";
            const dir = path.dirname(customOutputFile);
            const base = path.basename(customOutputFile, ext);
            destPath = path.isAbsolute(customOutputFile)
              ? path.join(dir, `${base}_${i + 1}${ext}`)
              : path.resolve(context.cwd, dir, `${base}_${i + 1}${ext}`);
          } else {
            const ext = path.extname(customOutputFile) ? "" : ".png";
            destPath = path.isAbsolute(customOutputFile)
              ? `${customOutputFile}${ext}`
              : path.resolve(context.cwd, `${customOutputFile}${ext}`);
          }
        } else {
          const fileName =
            images.length > 1 ? `gen_${stamp}_${i + 1}.png` : `gen_${stamp}.png`;
          destPath = path.resolve(context.cwd, fileName);
        }

        await mkdir(path.dirname(destPath), { recursive: true });
        await writeFile(destPath, Buffer.from(img.b64_json, "base64"));
        savedFiles.push(destPath);
      }

      content.push({
        type: "text",
        text:
          savedFiles.length === 1
            ? `Saved image to: ${savedFiles[0]}`
            : `Saved images to:\n` + savedFiles.map((file) => `- ${file}`).join("\n"),
      });

      return { content };
    },
  };
}
